name: Build Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # إجبار النظام على استخدام إصدار Gradle 8.7 تحديداً
      - name: Setup Gradle 8.7
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      # بناء الإضافة مباشرة باستخدام النظام المثبت بدلاً من gradlew المفقود
      - name: Build Carateen Extension
        run: gradle :CarateenProvider:assembleDebug

      # نضعه هنا (بعد عملية البناء مباشرة) لرفع الملف الناتج
      - name: Upload Extension File
        uses: actions/upload-artifact@v4
        with:
          name: Carateen-Plugin
          path: CarateenProvider/build/outputs/aar/*.aar
